### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yaa110** [alexforster/libbpf-sys#28]
version: 0.5.0-2
```
error[E0063]: missing fields `__bindgen_padding_0` and `__bindgen_padding_1` in initializer of `bpf_object_open_opts`
  --> src/bpf/object.rs:41:9
   |
41 |         libbpf_sys::bpf_object_open_opts {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `__bindgen_padding_0` and `__bindgen_padding_1`

For more information about this error, try `rustc --explain E0063`.
```
why are these paddings explicit? it is a breaking change that makes CI broken. please consider using another versioning scheme to avoid this kind of problems.

**Comment by alexforster** [comment]
I've added explicit padding like this because it turns out that [libbpf checks that struct padding is zero](https://github.com/libbpf/libbpf/blob/07ba0eeb8e0a4ed492464af55b0ca89a40161615/src/libbpf_internal.h#L241), for some bizarre reason.

This is the relevant PR: https://github.com/alexforster/libbpf-sys/issues/25

Once libbpf goes 1.0 (soon!) we'll start following SemVer.

**Comment by yaa110** [comment]
thanks
